import { Body, Controller, Get, Param, Patch, Post, Put, Query, Req, UseGuards } from '@nestjs/common';
import { validate as uuid } from 'uuid';
import { AuthenticatedRequest } from '../auth/authenticated-request';
import { PasswordReadyGuard } from '../auth/password-ready.guard';
import { SessionAuthGuard } from '../auth/session-auth.guard';
import { badRequest } from '../observability/http-errors';
import { SchedulingService } from './scheduling.service';
import { GoogleCalendarService } from './google-calendar.service';

@Controller('v1/admin/tenants/:tenantId/scheduling')
@UseGuards(SessionAuthGuard,PasswordReadyGuard)
export class SchedulingController {
  constructor(private readonly service:SchedulingService,private readonly google:GoogleCalendarService){}
  @Get() get(@Param('tenantId') tenantId:string,@Req() req:AuthenticatedRequest){valid(tenantId);return this.service.get(tenantId,req.actor.userId)}
  @Post('resources') create(@Param('tenantId') tenantId:string,@Body() body:unknown,@Req() req:AuthenticatedRequest){valid(tenantId);return this.service.createResource(tenantId,req.actor.userId,resource(body))}
  @Patch('resources/:resourceId') update(@Param('tenantId') tenantId:string,@Param('resourceId') resourceId:string,@Body() body:unknown,@Req() req:AuthenticatedRequest){valid(tenantId,resourceId);return this.service.updateResource(tenantId,req.actor.userId,resourceId,resource(body))}
  @Put('resources/:resourceId/availability') availability(@Param('tenantId') tenantId:string,@Param('resourceId') resourceId:string,@Body() body:unknown,@Req() req:AuthenticatedRequest){valid(tenantId,resourceId);return this.service.saveAvailability(tenantId,req.actor.userId,resourceId,rules(body))}
  @Put('resources/:resourceId/services') services(@Param('tenantId') tenantId:string,@Param('resourceId') resourceId:string,@Body() body:unknown,@Req() req:AuthenticatedRequest){valid(tenantId,resourceId);return this.service.saveServices(tenantId,req.actor.userId,resourceId,services(body))}
  @Post('calendar-sources') source(@Param('tenantId') tenantId:string,@Body() body:unknown,@Req() req:AuthenticatedRequest){valid(tenantId);return this.service.createCalendarSource(tenantId,req.actor.userId,calendar(body))}
  @Get('google-calendar/authorize') authorizeGoogle(@Param('tenantId') tenantId:string,@Req() req:AuthenticatedRequest){valid(tenantId);return this.google.authorizationUrl(tenantId,req.actor.userId)}
  @Get('calendar-sources/:sourceId/calendars') calendars(@Param('tenantId')tenantId:string,@Param('sourceId')sourceId:string,@Req()req:AuthenticatedRequest){valid(tenantId,sourceId);return this.google.calendars(tenantId,req.actor.userId,sourceId)}
  @Put('calendar-sources/:sourceId/strategy') strategy(@Param('tenantId')tenantId:string,@Param('sourceId')sourceId:string,@Body()body:unknown,@Req()req:AuthenticatedRequest){valid(tenantId,sourceId);const mode=(body as {mode?:unknown})?.mode;if(mode!=='global'&&mode!=='per_resource')throw badRequest('VALIDATION_ERROR','Invalid calendar strategy');return this.service.saveCalendarStrategy(tenantId,req.actor.userId,sourceId,mode)}
  @Put('calendar-sources/:sourceId/assignment') assignment(@Param('tenantId')tenantId:string,@Param('sourceId')sourceId:string,@Body()body:unknown,@Req()req:AuthenticatedRequest){valid(tenantId,sourceId);return this.service.saveCalendarAssignment(tenantId,req.actor.userId,sourceId,assignment(body))}
  @Get('availability') slots(@Param('tenantId') tenantId:string,@Query() query:Record<string,unknown>,@Req() req:AuthenticatedRequest){valid(tenantId);return this.service.availability(tenantId,req.actor.userId,availability(query))}
  @Post('appointments/hold') hold(@Param('tenantId') tenantId:string,@Body() body:unknown,@Req() req:AuthenticatedRequest){valid(tenantId);return this.service.hold(tenantId,req.actor.userId,hold(body))}
  @Patch('appointments/:appointmentId') transition(@Param('tenantId') tenantId:string,@Param('appointmentId') appointmentId:string,@Body() body:unknown,@Req() req:AuthenticatedRequest){valid(tenantId,appointmentId);return this.service.transition(tenantId,req.actor.userId,appointmentId,transition(body))}
}
function valid(...values:string[]){if(values.some(value=>!uuid(value)))throw badRequest('VALIDATION_ERROR','Identifiers must be UUIDs')}
function resource(body:unknown){const value=body as Record<string,unknown>;const name=typeof value?.name==='string'?value.name.trim():'';const resourceType=String(value?.resourceType??'');const status=String(value?.status??'active');if(!name||name.length>120||!['person','space','equipment','other'].includes(resourceType)||!['active','inactive','archived'].includes(status))throw badRequest('VALIDATION_ERROR','Invalid resource');return{name,resourceType,status,attributes:typeof value.attributes==='object'&&value.attributes&&!Array.isArray(value.attributes)?value.attributes:{}}}
function rules(body:unknown){const value=(body as {rules?:unknown})?.rules;if(!Array.isArray(value)||value.length>50)throw badRequest('VALIDATION_ERROR','Invalid availability');return value.map(item=>{const row=item as Record<string,unknown>;const day=Number(row.dayOfWeek),startsAt=String(row.startsAt??''),endsAt=String(row.endsAt??''),timezone=String(row.timezone??'');if(!Number.isInteger(day)||day<0||day>6||!/^([01]\d|2[0-3]):[0-5]\d$/.test(startsAt)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(endsAt)||startsAt>=endsAt||!timezone||timezone.length>80)throw badRequest('VALIDATION_ERROR','Invalid availability rule');return{dayOfWeek:day,startsAt,endsAt,timezone}})}
function services(body:unknown){const values=(body as {catalogItemIds?:unknown})?.catalogItemIds;if(!Array.isArray(values)||values.some(value=>typeof value!=='string'||!uuid(value)))throw badRequest('VALIDATION_ERROR','Invalid service identifiers');return[...new Set(values as string[])]}
function calendar(body:unknown){const value=body as Record<string,unknown>;const provider=String(value?.provider??''),displayName=typeof value?.displayName==='string'?value.displayName.trim():'';if(!['internal','google_calendar','microsoft_outlook','calendly','custom_api'].includes(provider)||!displayName||displayName.length>120)throw badRequest('VALIDATION_ERROR','Invalid calendar source');return{provider,displayName}}
function assignment(body:unknown){const value=body as Record<string,unknown>;const globalCalendarId=typeof value?.globalCalendarId==='string'&&value.globalCalendarId.trim()?value.globalCalendarId.trim():null;const resourceAssignments=value?.resourceAssignments;if(globalCalendarId&&globalCalendarId.length>1024)throw badRequest('VALIDATION_ERROR','Invalid global calendar');if(!Array.isArray(resourceAssignments))throw badRequest('VALIDATION_ERROR','Invalid resource calendar assignments');const rows=resourceAssignments.map(item=>{const row=item as Record<string,unknown>;const resourceId=String(row?.resourceId??''),calendarId=String(row?.calendarId??'').trim();valid(resourceId);if(!calendarId||calendarId.length>1024)throw badRequest('VALIDATION_ERROR','Invalid resource calendar assignment');return{resourceId,calendarId}});if(new Set(rows.map(row=>row.resourceId)).size!==rows.length||new Set(rows.map(row=>row.calendarId)).size!==rows.length)throw badRequest('VALIDATION_ERROR','Calendar assignments must be unique');return{globalCalendarId,resourceAssignments:rows}}
function date(value:unknown,name:string){if(typeof value!=='string'||!value||Number.isNaN(Date.parse(value)))throw badRequest('VALIDATION_ERROR',`${name} must be an ISO date`);return value}
function availability(value:Record<string,unknown>){const catalogItemId=String(value.catalogItemId??'');valid(catalogItemId);const from=date(value.from,'from'),until=date(value.until,'until'),limit=value.limit===undefined?20:Number(value.limit);if(new Date(until)<=new Date(from)||!Number.isInteger(limit)||limit<1||limit>100)throw badRequest('VALIDATION_ERROR','Invalid availability range');return{catalogItemId,from,until,limit}}
function hold(body:unknown){const value=body as Record<string,unknown>;const catalogItemId=String(value?.catalogItemId??''),contactId=String(value?.contactId??''),resourceId=String(value?.resourceId??''),commercialRequestId=value?.commercialRequestId?String(value.commercialRequestId):null;valid(catalogItemId,contactId,resourceId,...(commercialRequestId?[commercialRequestId]:[]));const startsAt=date(value.startsAt,'startsAt'),endsAt=date(value.endsAt,'endsAt'),timezone=String(value.timezone??''),idempotencyKey=String(value.idempotencyKey??'');if(new Date(endsAt)<=new Date(startsAt)||!timezone||timezone.length>80||!idempotencyKey||idempotencyKey.length>200)throw badRequest('VALIDATION_ERROR','Invalid appointment hold');return{catalogItemId,contactId,resourceId,commercialRequestId,startsAt,endsAt,timezone,idempotencyKey}}
function transition(body:unknown){const value=body as Record<string,unknown>;const action=String(value?.action??'');if(!['confirm','reschedule','cancel','complete'].includes(action))throw badRequest('VALIDATION_ERROR','Invalid appointment action');const startsAt=value.startsAt?date(value.startsAt,'startsAt'):null,endsAt=value.endsAt?date(value.endsAt,'endsAt'):null;if(action==='reschedule'&&(!startsAt||!endsAt||new Date(endsAt)<=new Date(startsAt)))throw badRequest('VALIDATION_ERROR','Reschedule requires a valid range');return{action,startsAt,endsAt}}
