import { Injectable } from '@nestjs/common';
import { PoolClient } from 'pg';
import { v7 as uuidv7 } from 'uuid';
import { DatabaseService } from '../database/database.service';
import { conflict,forbidden,notFound } from '../observability/http-errors';

type ResourceInput={name:string;resourceType:string;status:string;attributes:object};
type Rule={dayOfWeek:number;startsAt:string;endsAt:string;timezone:string};
@Injectable()
export class SchedulingService {
  constructor(private readonly db:DatabaseService){}
  get(tenantId:string,userId:string){return this.db.withTenantTransaction(tenantId,async client=>{const canManage=await this.access(client,userId);const [resources,rules,links,services,sources]=await Promise.all([
    client.query(`select id,resource_type,name,status,attributes from app.booking_resources where status<>'archived' order by name`),
    client.query(`select id,resource_id,day_of_week,starts_at::text,ends_at::text,timezone,status from app.resource_availability_rules where status='active' order by day_of_week,starts_at`),
    client.query(`select link.resource_id,link.calendar_source_id,link.external_calendar_id,link.status from app.resource_calendar_links link where link.status<>'disabled'`),
    client.query(`select item.id,item.name,item.duration_minutes,item.offering_type,link.resource_id from app.catalog_items item left join app.service_resource_links link on link.tenant_id=item.tenant_id and link.catalog_item_id=item.id and link.status='active' where item.status='active' and (item.booking_required or item.offering_type in('service','appointment')) order by item.name`),
    client.query(`select id,provider,display_name,status,last_synced_at,last_error_code,scheduling_mode,global_external_calendar_id from app.calendar_sources order by display_name`),
  ]);return{canManage,resources:resources.rows.map(resource=>({id:resource.id,resourceType:resource.resource_type,name:resource.name,status:resource.status,attributes:resource.attributes,rules:rules.rows.filter(rule=>rule.resource_id===resource.id).map(rule=>({id:rule.id,dayOfWeek:rule.day_of_week,startsAt:rule.starts_at.slice(0,5),endsAt:rule.ends_at.slice(0,5),timezone:rule.timezone})),serviceIds:services.rows.filter(service=>service.resource_id===resource.id).map(service=>service.id),calendarLinks:links.rows.filter(link=>link.resource_id===resource.id).map(link=>({calendarSourceId:link.calendar_source_id,externalCalendarId:link.external_calendar_id,status:link.status}))})),services:[...new Map(services.rows.map(row=>[row.id,{id:row.id,name:row.name,durationMinutes:row.duration_minutes,offeringType:row.offering_type}])).values()],calendarSources:sources.rows.map(row=>({id:row.id,provider:row.provider,displayName:row.display_name,status:row.status,lastSyncedAt:row.last_synced_at,lastErrorCode:row.last_error_code,schedulingMode:row.scheduling_mode,globalCalendarId:row.global_external_calendar_id}))}})}
  createResource(tenantId:string,userId:string,input:ResourceInput){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);const id=uuidv7();await client.query(`insert into app.booking_resources(id,tenant_id,resource_type,name,status,attributes) values($1,$2,$3,$4,$5,$6::jsonb)`,[id,tenantId,input.resourceType,input.name,input.status,JSON.stringify(input.attributes)]);return{resourceId:id}})}
  updateResource(tenantId:string,userId:string,id:string,input:ResourceInput){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);const result=await client.query(`update app.booking_resources set resource_type=$2,name=$3,status=$4,attributes=$5::jsonb,updated_at=now() where id=$1 returning id`,[id,input.resourceType,input.name,input.status,JSON.stringify(input.attributes)]);if(!result.rows[0])throw notFound('BOOKING_RESOURCE_NOT_FOUND','Booking resource was not found');return{updated:true}})}
  saveAvailability(tenantId:string,userId:string,resourceId:string,rules:Rule[]){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);if(!(await client.query(`select 1 from app.booking_resources where id=$1 and status<>'archived'`,[resourceId])).rows[0])throw notFound('BOOKING_RESOURCE_NOT_FOUND','Booking resource was not found');await client.query(`update app.resource_availability_rules set status='inactive',updated_at=now() where resource_id=$1 and status='active'`,[resourceId]);for(const rule of rules)await client.query(`insert into app.resource_availability_rules(id,tenant_id,resource_id,day_of_week,starts_at,ends_at,timezone,status) values($1,$2,$3,$4,$5,$6,$7,'active') on conflict(tenant_id,resource_id,day_of_week,starts_at,ends_at) do update set timezone=excluded.timezone,status='active',updated_at=now()`,[uuidv7(),tenantId,resourceId,rule.dayOfWeek,rule.startsAt,rule.endsAt,rule.timezone]);return{saved:true}})}
  saveServices(tenantId:string,userId:string,resourceId:string,ids:string[]){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);await client.query(`update app.service_resource_links set status='inactive',updated_at=now() where resource_id=$1`,[resourceId]);for(const id of ids)await client.query(`insert into app.service_resource_links(tenant_id,catalog_item_id,resource_id,status) values($1,$2,$3,'active') on conflict(tenant_id,catalog_item_id,resource_id) do update set status='active',updated_at=now()`,[tenantId,id,resourceId]);return{saved:true}})}
  createCalendarSource(tenantId:string,userId:string,input:{provider:string;displayName:string}){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);const id=uuidv7();await client.query(`insert into app.calendar_sources(id,tenant_id,provider,display_name,status) values($1,$2,$3,$4,'disconnected')`,[id,tenantId,input.provider,input.displayName]);return{calendarSourceId:id,status:'disconnected'}})}
  saveCalendarStrategy(tenantId:string,userId:string,sourceId:string,mode:'global'|'per_resource'){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);const result=await client.query(`update app.calendar_sources set scheduling_mode=$2,updated_at=now() where id=$1 and provider='google_calendar' returning id,scheduling_mode`,[sourceId,mode]);if(!result.rows[0])throw notFound('CALENDAR_SOURCE_NOT_FOUND','Calendar source was not found');return{calendarSourceId:sourceId,schedulingMode:mode}})}
  saveCalendarAssignment(tenantId:string,userId:string,sourceId:string,input:{globalCalendarId:string|null;resourceAssignments:{resourceId:string;calendarId:string}[]}){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);const source=await client.query<{scheduling_mode:'global'|'per_resource'}>(`select scheduling_mode from app.calendar_sources where id=$1 and provider='google_calendar' and status='connected'`,[sourceId]);if(!source.rows[0])throw notFound('CALENDAR_SOURCE_NOT_FOUND','Connected Google Calendar source was not found');if(source.rows[0].scheduling_mode==='global'&&!input.globalCalendarId)throw conflict('GLOBAL_CALENDAR_REQUIRED','Select a global calendar');if(source.rows[0].scheduling_mode==='per_resource'&&!input.resourceAssignments.length)throw conflict('RESOURCE_CALENDARS_REQUIRED','Assign at least one resource calendar');for(const assignment of input.resourceAssignments){if(!(await client.query(`select 1 from app.booking_resources where id=$1 and status='active'`,[assignment.resourceId])).rows[0])throw notFound('BOOKING_RESOURCE_NOT_FOUND','Booking resource was not found')}await client.query(`update app.calendar_sources set global_external_calendar_id=$2,updated_at=now() where id=$1`,[sourceId,source.rows[0].scheduling_mode==='global'?input.globalCalendarId:null]);await client.query(`update app.resource_calendar_links set status='disabled' where calendar_source_id=$1 and status<>'disabled'`,[sourceId]);if(source.rows[0].scheduling_mode==='per_resource')for(const assignment of input.resourceAssignments)await client.query(`insert into app.resource_calendar_links(id,tenant_id,resource_id,calendar_source_id,external_calendar_id,status) values($1,$2,$3,$4,$5,'active') on conflict(tenant_id,calendar_source_id,external_calendar_id) do update set resource_id=excluded.resource_id,status='active'`,[uuidv7(),tenantId,assignment.resourceId,sourceId,assignment.calendarId]);return{calendarSourceId:sourceId,saved:true}})}
  availability(tenantId:string,userId:string,input:{catalogItemId:string;from:string;until:string;limit:number}){return this.db.withTenantTransaction(tenantId,async client=>{await this.access(client,userId);const result=await client.query(`select resource_id,resource_name,starts_at,ends_at,timezone from app.find_available_slots($1,$2,$3,$4)`,[input.catalogItemId,input.from,input.until,input.limit]);return{slots:result.rows.map(row=>({resourceId:row.resource_id,resourceName:row.resource_name,startsAt:row.starts_at,endsAt:row.ends_at,timezone:row.timezone}))}})}
  hold(tenantId:string,userId:string,input:{catalogItemId:string;contactId:string;resourceId:string;commercialRequestId:string|null;startsAt:string;endsAt:string;timezone:string;idempotencyKey:string}){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);const id=uuidv7();try{const result=await client.query<{id:string}>(`select app.hold_appointment($1,$2,$3,$4,$5,$6,$7,$8,$9,10) id`,[id,input.catalogItemId,input.contactId,input.resourceId,input.commercialRequestId,input.idempotencyKey,input.startsAt,input.endsAt,input.timezone]);return{appointmentId:result.rows[0].id,status:'held',holdMinutes:10}}catch(error){if((error as {code?:string}).code==='23P01')throw conflict('APPOINTMENT_SLOT_TAKEN','The selected appointment slot is no longer available');throw error}})}
  transition(tenantId:string,userId:string,appointmentId:string,input:{action:string;startsAt:string|null;endsAt:string|null}){return this.db.withTenantTransaction(tenantId,async client=>{await this.manage(client,userId);try{const result=await client.query<{event_type:string}>(`select app.transition_appointment($1,$2,$3,$4) event_type`,[appointmentId,input.action,input.startsAt,input.endsAt]);await client.query(`insert into app.outbox_events(id,tenant_id,event_type,aggregate_type,aggregate_id,correlation_id,payload_schema_version,payload) values($1,$2,$3,'appointment',$4,$5,1,jsonb_build_object('appointmentId',($4::uuid)::text))`,[uuidv7(),tenantId,result.rows[0].event_type,appointmentId,uuidv7()]);return{appointmentId,eventType:result.rows[0].event_type}}catch(error){if(['23514','P0002'].includes((error as {code?:string}).code??''))throw conflict('APPOINTMENT_TRANSITION_REJECTED',(error as Error).message);throw error}})}
  private async access(client:PoolClient,userId:string){const membership=await client.query(`select role from app.tenant_users where tenant_id=app.current_tenant_id() and user_id=$1 and status='active'`,[userId]);if(membership.rows[0])return membership.rows[0].role!=='viewer';const platform=await client.query(`select app.can_manage_channel_connections($1) allowed`,[userId]);if(!platform.rows[0]?.allowed)throw forbidden('SCHEDULING_FORBIDDEN','Actor cannot access scheduling');return true}
  private async manage(client:PoolClient,userId:string){if(!await this.access(client,userId))throw forbidden('SCHEDULING_FORBIDDEN','Actor cannot manage scheduling')}
}
