import { SchedulingService } from './scheduling.service';

describe('SchedulingService',()=>{
  it('creates a provider-neutral booking resource inside the tenant transaction',async()=>{
    const queries:string[]=[];const client={query:jest.fn(async(sql:string)=>{queries.push(sql);if(sql.includes('from app.tenant_users'))return{rows:[{role:'admin'}]};return{rows:[]}})};const db={withTenantTransaction:(_tenant:string,operation:(client:unknown)=>unknown)=>operation(client)} as never;
    const result=await new SchedulingService(db).createResource('tenant-1','user-1',{name:'Station 1',resourceType:'space',status:'active',attributes:{}});
    expect(result.resourceId).toBeTruthy();expect(queries.some(sql=>sql.includes('insert into app.booking_resources'))).toBe(true);
  });
  it('replaces active weekly rules without deleting their history',async()=>{
    const queries:string[]=[];const client={query:jest.fn(async(sql:string)=>{queries.push(sql);if(sql.includes('from app.tenant_users'))return{rows:[{role:'operator'}]};if(sql.includes('select 1 from app.booking_resources'))return{rows:[{exists:true}]};return{rows:[]}})};const db={withTenantTransaction:(_tenant:string,operation:(client:unknown)=>unknown)=>operation(client)} as never;
    await new SchedulingService(db).saveAvailability('tenant-1','user-1','resource-1',[{dayOfWeek:1,startsAt:'09:00',endsAt:'18:00',timezone:'America/Bogota'}]);
    expect(queries.some(sql=>sql.includes("set status='inactive'"))).toBe(true);expect(queries.some(sql=>sql.includes('insert into app.resource_availability_rules'))).toBe(true);
  });
  it('denies resource changes to viewers',async()=>{const client={query:jest.fn(async()=>({rows:[{role:'viewer'}]}))};const db={withTenantTransaction:(_tenant:string,operation:(client:unknown)=>unknown)=>operation(client)} as never;await expect(new SchedulingService(db).createResource('tenant-1','viewer-1',{name:'Blocked',resourceType:'person',status:'active',attributes:{}})).rejects.toThrow('Actor cannot manage scheduling')});
  it('publishes an outbox event after confirming an appointment',async()=>{const queries:string[]=[];const client={query:jest.fn(async(sql:string)=>{queries.push(sql);if(sql.includes('from app.tenant_users'))return{rows:[{role:'operator'}]};if(sql.includes('transition_appointment'))return{rows:[{event_type:'appointment.confirmed'}]};return{rows:[]}})};const db={withTenantTransaction:(_tenant:string,operation:(client:unknown)=>unknown)=>operation(client)} as never;const result=await new SchedulingService(db).transition('tenant-1','user-1','appointment-1',{action:'confirm',startsAt:null,endsAt:null});expect(result.eventType).toBe('appointment.confirmed');expect(queries.some(sql=>sql.includes('insert into app.outbox_events'))).toBe(true)});
  it('stores the selected global Google calendar',async()=>{const queries:{sql:string;params?:unknown[]}[]=[];const client={query:jest.fn(async(sql:string,params?:unknown[])=>{queries.push({sql,params});if(sql.includes('from app.tenant_users'))return{rows:[{role:'admin'}]};if(sql.includes('select scheduling_mode'))return{rows:[{scheduling_mode:'global'}]};return{rows:[]}})};const db={withTenantTransaction:(_tenant:string,operation:(client:unknown)=>unknown)=>operation(client)} as never;await new SchedulingService(db).saveCalendarAssignment('tenant-1','user-1','source-1',{globalCalendarId:'business@example.com',resourceAssignments:[]});expect(queries.some(query=>query.sql.includes('global_external_calendar_id')&&query.params?.[1]==='business@example.com')).toBe(true)});
  it('stores one Google calendar per active resource',async()=>{const queries:string[]=[];const client={query:jest.fn(async(sql:string)=>{queries.push(sql);if(sql.includes('from app.tenant_users'))return{rows:[{role:'admin'}]};if(sql.includes('select scheduling_mode'))return{rows:[{scheduling_mode:'per_resource'}]};if(sql.includes('select 1 from app.booking_resources'))return{rows:[{}]};return{rows:[]}})};const db={withTenantTransaction:(_tenant:string,operation:(client:unknown)=>unknown)=>operation(client)} as never;await new SchedulingService(db).saveCalendarAssignment('tenant-1','user-1','source-1',{globalCalendarId:null,resourceAssignments:[{resourceId:'resource-1',calendarId:'barber@example.com'}]});expect(queries.some(sql=>sql.includes('insert into app.resource_calendar_links'))).toBe(true)});
});
